-- Script generated by Redgate Compare v1.11.2.9177

SET check_function_bodies = false;


DO language plpgsql $$BEGIN RAISE NOTICE 'Creating public.feed_post_id_seq...';END$$;
CREATE SEQUENCE public.feed_post_id_seq
AS integer
INCREMENT BY 1
MINVALUE 1
MAXVALUE 2147483647
START 1
CACHE 1
NO CYCLE;


DO language plpgsql $$BEGIN RAISE NOTICE 'Creating public.feed_post...';END$$;
CREATE TABLE public.feed_post (
    id integer NOT NULL DEFAULT nextval('public.feed_post_id_seq'::regclass),
    "createdAt" timestamp without time zone,
    body character varying,
    title character varying
);


DO language plpgsql $$BEGIN RAISE NOTICE 'Altering public.feed_post_id_seq...';END$$;
ALTER SEQUENCE public.feed_post_id_seq OWNED BY public.feed_post.id;


DO language plpgsql $$BEGIN RAISE NOTICE 'Creating public.feed_comment_id_seq...';END$$;
CREATE SEQUENCE public.feed_comment_id_seq
AS integer
INCREMENT BY 1
MINVALUE 1
MAXVALUE 2147483647
START 1
CACHE 1
NO CYCLE;


DO language plpgsql $$BEGIN RAISE NOTICE 'Creating public.feed_comment...';END$$;
CREATE TABLE public.feed_comment (
    id integer NOT NULL DEFAULT nextval('public.feed_comment_id_seq'::regclass),
    text character varying,
    "createdAt" timestamp without time zone,
    postid integer
);


DO language plpgsql $$BEGIN RAISE NOTICE 'Altering public.feed_comment_id_seq...';END$$;
ALTER SEQUENCE public.feed_comment_id_seq OWNED BY public.feed_comment.id;
SET check_function_bodies = true;
